defaults:
  - aff_model/labeling@labeling: simulation
  - env: env_labeling
  - scene: empty_table
  - robot: panda
  - camera_conf@cameras: static_and_gripper
  - paths: general_paths
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

#Environment
output_size:
  static: 200
  gripper: 64
mask_on_close: True
save_viz: False
euler_obs: True
frames_before_saving: 10000
viz: false

# To write all data to a single split
output_cfg:
  single_split: False  # True if all the images in the play_data_dir belong to a single split, otherwise they will be split into validation and training
  save_split: "training"
  multiclass: False

# For collecting dataset with playdata
dataset_name: simulation
play_data_dir: ${paths.datasets}/playdata/${dataset_name}

# Output directory where dataset will be stored
output_dir: ${paths.datasets}/${dataset_name}/


hydra:
  run:
    dir: ./hydra_outputs/datacollection/${now:%Y-%m-%d}_${now:%H-%M-%S}
