parent_folder: ../
vapo_path: ${paths.parent_folder}/vapo_aff/
vr_data: ${paths.vapo_path}/VREnv/data/
scripts: ${paths.vapo_path}/scripts/
camera_config: ${paths.vapo_path}/config/camera_conf/cameras/

# Trained affordance models
trained_models: ${paths.vapo_path}/trained_models/

# For training affordance model
datasets: ${paths.vapo_path}/datasets/
