parent_folder: ../
vapo_path: ${paths.parent_folder}/vapo_affordance_model_only/
vr_data: ${paths.vapo_path}/VREnv/data/
scripts: ${paths.vapo_path}/scripts/

# Trained affordance models
trained_models: ${paths.vapo_path}/trained_models/

# For training affordance model
datasets: ${paths.vapo_path}/datasets/
